export default {
  id: 181808,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 2,
      known_for_department: "Acting",
      name: "Mark Hamill",
      original_name: "Mark Hamill",
      popularity: 20.774,
      profile_path: "/zMQ93JTLW8KxusKhOlHFZhih3YQ.jpg",
      cast_id: 14,
      character: "Luke Skywalker / Dobbu Scay (voice)",
      credit_id: "5679cdd4c3a3685bbf000206",
      order: 0
    },
    {
      adult: false,
      gender: 1,
      id: 4,
      known_for_department: "Acting",
      name: "Carrie Fisher",
      original_name: "Carrie Fisher",
      popularity: 11.698,
      profile_path: "/rfJtncHewKVnHjqpIZvjn24ESeC.jpg",
      cast_id: 15,
      character: "General Leia Organa",
      credit_id: "567aa394c3a3685bdf00266a",
      order: 1
    },
    {
      adult: false,
      gender: 2,
      id: 1023139,
      known_for_department: "Acting",
      name: "Adam Driver",
      original_name: "Adam Driver",
      popularity: 23.795,
      profile_path: "/rsjwgpV2OukxOJ9HEiEyf4qu1vR.jpg",
      cast_id: 13,
      character: "Kylo Ren / Ben Solo",
      credit_id: "5679cdbd92514106f50001e9",
      order: 2
    },
    {
      adult: false,
      gender: 1,
      id: 1315036,
      known_for_department: "Acting",
      name: "Daisy Ridley",
      original_name: "Daisy Ridley",
      popularity: 36.425,
      profile_path: "/qPzTLRxTWwhOXaqwMRuZ9oTKZtP.jpg",
      cast_id: 11,
      character: "Rey",
      credit_id: "562fdd999251413b460008ad",
      order: 3
    },
    {
      adult: false,
      gender: 2,
      id: 236695,
      known_for_department: "Acting",
      name: "John Boyega",
      original_name: "John Boyega",
      popularity: 8.529,
      profile_path: "/3153CfpgZQXTzCY0i74WpJumMQe.jpg",
      cast_id: 12,
      character: "Finn",
      credit_id: "562fdda8c3a3681b5900dd91",
      order: 4
    },
    {
      adult: false,
      gender: 2,
      id: 25072,
      known_for_department: "Acting",
      name: "Oscar Isaac",
      original_name: "Oscar Isaac",
      popularity: 56.715,
      profile_path: "/dW5U5yrIIPmMjRThR9KT2xH6nTz.jpg",
      cast_id: 6,
      character: "Poe Dameron",
      credit_id: "55e96032c3a3682c6b0053f2",
      order: 5
    },
    {
      adult: false,
      gender: 2,
      id: 1333,
      known_for_department: "Acting",
      name: "Andy Serkis",
      original_name: "Andy Serkis",
      popularity: 22.239,
      profile_path: "/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg",
      cast_id: 29,
      character: "Supreme Leader Snoke",
      credit_id: "57884cd292514138df001b72",
      order: 6
    },
    {
      adult: false,
      gender: 1,
      id: 1267329,
      known_for_department: "Acting",
      name: "Lupita Nyong'o",
      original_name: "Lupita Nyong'o",
      popularity: 10.364,
      profile_path: "/y40Wu1T742kynOqtwXASc5Qgm49.jpg",
      cast_id: 27,
      character: "Maz Kanata",
      credit_id: "57884c7ac3a36832e40026df",
      order: 7
    },
    {
      adult: false,
      gender: 2,
      id: 93210,
      known_for_department: "Acting",
      name: "Domhnall Gleeson",
      original_name: "Domhnall Gleeson",
      popularity: 26.093,
      profile_path: "/uDbwncuKlqL0fAuucXSvgakJDrc.jpg",
      cast_id: 26,
      character: "General Hux",
      credit_id: "57884c66c3a36832e40026d3",
      order: 8
    },
    {
      adult: false,
      gender: 2,
      id: 6,
      known_for_department: "Acting",
      name: "Anthony Daniels",
      original_name: "Anthony Daniels",
      popularity: 9.859,
      profile_path: "/7kR4kwXtvXtvrsxWeX3QLX5NS5V.jpg",
      cast_id: 35,
      character: "C-3PO",
      credit_id: "582bfe12c3a36872cf0047c0",
      order: 9
    },
    {
      adult: false,
      gender: 1,
      id: 1011904,
      known_for_department: "Acting",
      name: "Gwendoline Christie",
      original_name: "Gwendoline Christie",
      popularity: 15.892,
      profile_path: "/kmlv5i02n3zKryBr2W3kSeWVKTD.jpg",
      cast_id: 17,
      character: "Captain Phasma",
      credit_id: "567aa55ac3a3685bdf0026d3",
      order: 10
    },
    {
      adult: false,
      gender: 1,
      id: 1663195,
      known_for_department: "Acting",
      name: "Kelly Marie Tran",
      original_name: "Kelly Marie Tran",
      popularity: 9.817,
      profile_path: "/2YuymbQfIlaUx8xtAxL5OOCsw6H.jpg",
      cast_id: 33,
      character: "Rose Tico",
      credit_id: "582bfd2a92514111b7004391",
      order: 11
    },
    {
      adult: false,
      gender: 1,
      id: 4784,
      known_for_department: "Acting",
      name: "Laura Dern",
      original_name: "Laura Dern",
      popularity: 26.472,
      profile_path: "/gB9PnGEvxKg33OSlcqptQwTBwPE.jpg",
      cast_id: 32,
      character: "Vice Admiral Amilyn Holdo",
      credit_id: "582bfd2092514111ac004664",
      order: 12
    },
    {
      adult: false,
      gender: 2,
      id: 1121,
      known_for_department: "Acting",
      name: "Benicio del Toro",
      original_name: "Benicio del Toro",
      popularity: 18.322,
      profile_path: "/cVh4UgCMu6aAkZ2BqymTLV86FzZ.jpg",
      cast_id: 7,
      character: "DJ",
      credit_id: "55e960409251413e3a005761",
      order: 13
    },
    {
      adult: false,
      gender: 2,
      id: 7908,
      known_for_department: "Acting",
      name: "Frank Oz",
      original_name: "Frank Oz",
      popularity: 10.356,
      profile_path: "/mb2JbT8s6LIgaxj6QTph0NW1pmI.jpg",
      cast_id: 53,
      character: "Yoda (voice)",
      credit_id: "5a313cb4925141033618b8b9",
      order: 14
    }
  ]
}